## active-projects.yaml
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: active-projects-hostpath
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
parameters:
  pvDir: /mnt/media/nvme1-3.7TiB/active-projects
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: active-projects
spec:
  storageClassName: active-projects-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3700Gi
