hub:
  config:
    JupyterHub:
      authenticator_class: nativeauthenticator.NativeAuthenticator
      admin_access: false
    Authenticator:
      admin_users:
        - langdon-holmes
        - wesley-morris
    NativeAuthenticator:
      enable_signup: true
      minimum_password_length: 8
      check_common_password: true
      ask_email_on_signup: true
      allow_2fa: false
  containerSecurityContext:
    allowPrivilegeEscalation: true
proxy:
  https:
    enabled: false
    hosts:
      - selnx-47ymrt3.vuds.vanderbilt.edu
  service:
    loadBalancerIP: 10.0.0.150
cull:
  enabled: true
  timeout: 10800
  every: 600
singleuser:
  defaultUrl: "/lab"
  extraEnv:
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    GRANT_SUDO: "yes"
    NOTEBOOK_ARGS: "--allow-root"
  uid: 0
  allowPrivilegeEscalation: True
  cmd: start-singleuser.sh
  image:
    name: langdonholmes/base-nlp
    tag: "cuda-11.7"
    pullPolicy: "Always"
  profileList:
    - display_name: "Normal Server"
      description: "Spawns a notebook server with no GPU access"
    - display_name: "RStudio Server"
      description: "Spawns an RStudio interface"
      kubespawner_override:
        image: langdonholmes/rstudio
        default_url: "/rstudio"
        pullPolicy: "Always"
    - display_name: "GPU Server"
      description: "Spawns a notebook server with GPU access."
      kubespawner_override:
        extra_resource_limits:
          nvidia.com/gpu: "1"
        extra_resource_guarantees:
          nvidia.com/gpu: "1"
  storage:
    capacity: 50Gi
    extraVolumes:
      - name: jupyterhub-active-projects
        persistentVolumeClaim:
          claimName: active-projects-storage-claim
      - name: jupyterhub-project-archive
        persistentVolumeClaim:
          claimName: project-archive-storage-claim
    extraVolumeMounts:
      - name: jupyterhub-active-projects
        mountPath: /home/jovyan/active-projects
      - name: jupyterhub-project-archive
        mountPath: /home/jovyan/project-archive
ingress:
  enabled: true
  hosts:
    - selnx-47ymrt3.vuds.vanderbilt.edu
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
