hub:
  config:
    JupyterHub:
      authenticator_class: nativeauthenticator.NativeAuthenticator
      admin_access: false
    Authenticator:
      admin_users:
        - langdon-holmes
        - wesley-morris
    NativeAuthenticator:
      enable_signup: true
      minimum_password_length: 8
      check_common_password: true
      ask_email_on_signup: true
      allow_2fa: false
      tos: "Unauthorized access to data (individually identifiable information) on this computer is a violation of federal law and will result in prosecution. Do you wish to continue?"
  containerSecurityContext:
    allowPrivilegeEscalation: true
  extraFiles:
    options_form:
      mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/custom_options_form.py
#    custom_pod_hook:
#      mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/custom_pod_hook.py
proxy:
  service:
    type: NodePort
    nodePorts:
      http: 30000
cull:
  enabled: true
  timeout: 10800
  every: 600
singleuser:
  defaultUrl: "/lab"
  extraEnv:
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    GRANT_SUDO: "yes"
    NOTEBOOK_ARGS: "--allow-root"
  uid: 0
  allowPrivilegeEscalation: True
  cmd: start-singleuser.sh
  image:
    name: langdonholmes/base-nlp
    tag: "cuda-11.8"
    pullPolicy: "IfNotPresent"
  profileList:
    - display_name: "Normal Server"
      description: "Spawns a notebook server with no GPU access"
    - display_name: "RStudio Server"
      description: "Spawns an RStudio interface"
      kubespawner_override:
        image: langdonholmes/rstudio
        default_url: "/rstudio"
        pullPolicy: "Always"
    - display_name: "GPU Server"
      description: "Spawns a notebook server with GPU access."
      kubespawner_override:
        extra_resource_limits:
          nvidia.com/gpu: "1"
        extra_resource_guarantees:
          nvidia.com/gpu: "1"
  storage:
    capacity: 50Gi
    extraVolumes:
      - name: jupyterhub-active-projects
        persistentVolumeClaim:
          claimName: active-projects
      - name: jupyterhub-project-archive
        persistentVolumeClaim:
          claimName: project-archive
    extraVolumeMounts:
      - name: jupyterhub-active-projects
        mountPath: /home/jovyan/active-projects
      - name: jupyterhub-project-archive
        mountPath: /home/jovyan/project-archive
ingress:
  enabled: true
  hosts:
    - jupyter.learlab.vanderbilt.edu
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
