## project-archive.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: project-archive-hostpath
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
parameters:
  pvDir: /media/nvme2-3.7TiB/project-archive
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-archive
spec:
  storageClassName: project-archive-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2000Gi
